on:
  workflow_dispatch:
  push:
    branches:
      - master
name: Bundle and Publish Sources

permissions:
  contents: write

jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run bundle
      - run: npx typedoc -out bundles/docs
        continue-on-error: true

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
